### ISSUE TITLE
Different color for the unselected roms in the list?

### ISSUE THREAD

**Issue by klundry** [pelle7/odroid-go-emu-launcher#1]
The color of the background and text of the unselected roms when scrolling through the list is very difficult to read. The selected rom is very visible but the unselected are almost unreadable. Could the color be changed to something a little lighter or with better contrast to make them more readable?

**Comment by ripper121** [comment]
+1

**Comment by pelle7** [comment]
You are right, I will adjust it. I can now properly test it :-) My original odroid-go display was very very bright, so I configured the colors wrong.....

**Comment by klundry** [comment]
That looks MUCH better!
